name: end-to-end tests
on:
    push:
        branches:
            - 'e2e/*'
jobs:
  run-tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: License Check
      run: |
        set -x
        git init
        git add --all
        git -c user.name="CI Bot" -c user.email="<>" commit -m "initial state"
        addlicense ./
        if [[ -n $(git status -s) ]]; then
          exit 1
        fi
    - name: Java Checkstyle
      timeout-minutes: 20
      run: |
        mvn checkstyle:check
    - name: Python Checkstyle
      timeout-minutes: 20
      run: |
        pylint --disable=F0401 --disable=W0511 --disable=E1101 --disable=R0801 --disable=R0903  ./src/*/*.py
        # disabled warnings: import loading, todos, function members, duplicate code, public methods
    - name: Setup Cluster
      run: |
        kind delete cluster 2>/dev/null
        kind create cluster
        kubectl get nodes
    - name: Deploy From Source
      run: |
        skaffold config set --global local-cluster true
        skaffold run --default-repo local
    - name: Wait For Pods
      timeout-minutes: 20
      run: |
        set -x
        kubectl wait --for=condition=available --timeout=500s deployment/accounts-db
        kubectl wait --for=condition=available --timeout=500s deployment/balancereader
        kubectl wait --for=condition=available --timeout=500s deployment/contacts
        kubectl wait --for=condition=available --timeout=500s deployment/frontend
        kubectl wait --for=condition=available --timeout=500s deployment/ledgerwriter
        kubectl wait --for=condition=available --timeout=500s deployment/ledger-db
        kubectl wait --for=condition=available --timeout=500s deployment/transactionhistory
        kubectl wait --for=condition=available --timeout=500s deployment/userservice
        kubectl wait --for=condition=available --timeout=500s deployment/loadgenerator
    - name: Smoke Test
      timeout-minutes: 5
      run: |
        set -x
        # start fresh loadgenerator pod
        kubectl delete pod -l app=loadgenerator
        # wait for requests to come in
        REQUEST_COUNT="0"
        while [[ "$REQUEST_COUNT"  -lt "100"  ]]; do
            sleep 5
            REQUEST_COUNT=$(kubectl logs -l app=loadgenerator | grep Total | awk '{print $2}')
        done
        # ensure there are no errors hitting endpoints
        ERROR_COUNT=$(kubectl logs -l app=loadgenerator | grep Total | awk '{print $3}' | sed "s/[(][^)]*[)]//g")
        if [[ "$ERROR_COUNT" -gt "0" ]]; then
          exit 1
        fi
  cypress-run:
        runs-on: self-hosted
        steps:
          - name: Checkout
            uses: actions/checkout@v1
          # Install NPM dependencies, cache them correctly
          # and run all Cypress tests
          - name: Cypress run
            uses: cypress-io/github-action@v1
            with:
                start: npm start