name: "Continuous Integration"
on:
  push:
    # run on pushes to master or release/*
    branches:
      - actions/*
  pull_request:
    # run on pull requests targeting master
    branches:
      - master
jobs:
  run-tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Port Forward
      run: |
        kubectl port-forward frontend-64756d9945-mbkfw 3000:8080 &
    - name: Ping
      run: |
        curl localhost:3000
    - name: UI tests
      run: |
        docker run -t -v $PWD/e2e:/e2e -w /e2e --network=host cypress/included:4.3.0
        sudo rm -rf e2e/cypress/screenshots
